In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# WEEK_03_NumPy


In [4]:
# numpy = libary of Python การจะใช้ libary ทุกครั้งต้อง Import เข้ามาก่อน
import numpy as np

In [1]:
#การลง Nummpy
!pip install numpy

In [5]:
#Check version Numbpy 
np.__version__

'1.19.5'

In [6]:
#Vector = 1D Array
a = np.array([1,2,3,4,5,6,7])
a


array([1, 2, 3, 4, 5, 6, 7])

In [9]:
#เลือกเอาตำเเหน่ง 2-5 ใน array มา output
a[2:5]

array([3, 4, 5])

In [12]:
#เลือกเอา 6 ตำเเหน่งมาจาก array แล้วมา output
a[:6]

array([1, 2, 3, 4, 5, 6])

In [13]:
#เลือกเอาตำเเหน่งตั้งแต่ 3 จนตำแหน่งสุดท้ายมาจาก array แล้วมา output
a[3:]

array([4, 5, 6, 7])

In [15]:
#เลือกเอาแค่ตำเเหน่งสุดท้ายมาจาก array แล้วมา output โดยใช้การ Negative number (-x) หรือ นับจากข้างหลังมาข้างหน้า
a[-1]

7

In [16]:
#เลือกเอาแค่ตำเเหน่งรองสุดท้ายมาจาก array แล้วมา output โดยใช้การ Negative number (-x) หรือ นับจากข้างหลังมาข้างหน้า
a[-2]

6

In [20]:
#เลือกเอาแค่ตำเเหน่ง 2 (positive number) จนไปถึง -3 (negative number) #ย้ำต้อง ตน. เป็น Array ที่ใกล้ๆกัน
a[2:-3]

array([3, 4])

In [21]:
#เลือกเอาแค่ทั้งตำเเหน่ง -5 (negative number) ซึ่งนับมาจากข้างหลังจาก Array
a[-5:]

array([3, 4, 5, 6, 7])

In [22]:
a[-5:-1]

array([3, 4, 5, 6])

In [23]:
#เช็คขนาดของ Array 1 D
np.size(a)

7

In [24]:
#Array 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
#Command shape in NumPy หมายถึงการให้ข้อมูลว่า array นั้นมีสมาชิก ""กี่ตัว กี่แถว กี่คอลัมน์ กี่ตาราง""
np.shape(a) # <--- Check array ข้างบนว่ามีกี่แถว กี่คอลัมน์

# ------------------โดย a[0,0] => [แถว , index]

(3, 3)

In [29]:
a[0,0]
# แถว 1 หลัก 1


1

In [31]:
# Output แถวที่ 1 ออกมาทั้งหมด (":" = เอาทั้งหมดของอถว 1) 
a[1,:] 

array([4, 5, 6])

In [32]:
# Output ออกมาแค่คอมลัมนับจากข้างหลัง
a[:,-1]

array([3, 6, 9])

In [33]:
a[:,1] = 0 
a

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [34]:
a[0:2,:] = 8
a

array([[8, 8, 8],
       [8, 8, 8],
       [7, 0, 9]])

In [35]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
# 0 = กว้าง ,1 = ยาว ,2 = สูง
np.size(a,0) 

4

In [37]:
#  Check หาว่าในArray นี้มีกี่ Dimension -> 2D Array
np.ndim(a) 

2

# Data is Matrix.

So, Matrix management == Data Management

rows = samples
columns = attributes, features

In [38]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [44]:
np.array(np_mix_matrix[:,1], dtype = int) 
#อย่าลืมใส่ Data type ด้วย!!!!!

array([2, 4, 6])

# Special Type of Matrix

In [40]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [42]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [43]:
c = np.full((5,5),8)
c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [47]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
c*d #np.eye(5) = np.full((5,5) => ขนาดของ matrix ต้องเท่ากันถึงจะคูณกันได้

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [50]:
np.matmul(c,d)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [53]:
np.sqrt(np.full((2,2),4)) #รากที่ 2 ของสี่

array([[2., 2.],
       [2., 2.]])

In [52]:
np.empty([5,5])

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

# Random


In [54]:
np.random.rand()

0.951981468120626

In [56]:
#random สุ่มเลข จำนวนเต็ม(int) มาในระยะ 10 ตัว
[np.random.randint(5) for i in range(10)]

[2, 4, 1, 4, 2, 4, 3, 2, 3, 1]

In [57]:
np.seed = 1
np.random.randint(2,5)

2

In [58]:
np.random.rand(5,5)

array([[0.15531718, 0.17474248, 0.98267589, 0.31178947, 0.97485996],
       [0.33893527, 0.26157209, 0.87992382, 0.86882893, 0.55900346],
       [0.6981758 , 0.37079673, 0.19708217, 0.22511165, 0.01162068],
       [0.67692946, 0.74030065, 0.68690219, 0.42566808, 0.63088305],
       [0.97319069, 0.09539532, 0.08882099, 0.17097053, 0.85672508]])

In [60]:
np.round(np.random.rand(5,5))

array([[0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 0., 1., 1., 0.],
       [0., 1., 1., 1., 1.]])

# EX1


In [61]:
# Ex 1. Please use random to generate this output
# ...


In [66]:
#anwser 
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([10,  8,  9,  8,  4])

# EX2

In [62]:
#Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
#
#
#

In [67]:
#Anwser
np_matrix = np.random.rand(10,5)
np_matrix[:, -1] = np.round(np_matrix[:, -1])
np_matrix

array([[0.09711629, 0.18884341, 0.87747016, 0.76110567, 0.        ],
       [0.45727863, 0.19784749, 0.05467508, 0.2803923 , 0.        ],
       [0.3575838 , 0.37270718, 0.10628675, 0.94961983, 0.        ],
       [0.65447167, 0.68626105, 0.85690483, 0.68584427, 0.        ],
       [0.7628076 , 0.27497435, 0.96523318, 0.9553363 , 0.        ],
       [0.11088783, 0.21090248, 0.03927677, 0.8079324 , 1.        ],
       [0.57972119, 0.30706019, 0.63436013, 0.48181503, 1.        ],
       [0.63332996, 0.79581742, 0.50911195, 0.59246804, 1.        ],
       [0.52979826, 0.9719688 , 0.23623042, 0.01739503, 1.        ],
       [0.37042127, 0.77932924, 0.99739221, 0.90864225, 1.        ]])

# EX3


In [63]:
#Ex 3. Why we cannot use this index ? Please fix it !!
idx = [1,2,3,4,5]
np_matrix[idx,:]

NameError: name 'np_matrix' is not defined

In [71]:
#Anwser
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]
idx

[1, 2, 3, 4, 5]

# EX4

In [64]:
# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
# Then, randomly create a label vector for 10 samples. 
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

In [81]:
#Anwser
rng = np.random.RandomState(0)
main_matrix = rng.randint(10 ,size=(10,5))
main_matrix

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0]])

In [76]:
rng = np.random.RandomState(0)
vertor = rng.randint(2, size=(10))
vertor

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [82]:
main_matrix[np.where(vertor==0)]

array([[5, 0, 3, 3, 7],
       [6, 7, 7, 8, 1]])

In [83]:
main_matrix[np.where(vertor==1)]

array([[9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0]])